use super::super::img::compute::ComputeConvolution;
use sheets::Response;
use sheets::spreadsheets::Spreadsheets;
use sheets::types::{
    AppendDimensionRequest, BatchUpdateSpreadsheetRequest, BatchUpdateSpreadsheetResponse, CellData, CellFormat, Color,
    Dimension, DimensionProperties, DimensionRange, GridRange, Request, RowData,
    UpdateCellsRequest, UpdateDimensionPropertiesRequest,
};
pub async fn draw_in_sheets(
    pixels: &ComputeConvolution,
    spreadsheet: &Spreadsheets,
    spreadsheet_id: &str,
) -> Result<Response<BatchUpdateSpreadsheetResponse>, Box<dyn std::error::Error>> {
    let height = pixels.computed_pixels.len();
    if height == 0 {
        return Err("Empty pixel data".into());
    }
    let width = pixels.computed_pixels[0].len();
    if width == 0 {
        return Err("Empty row in pixel data".into());
    }

    let mut rows: Vec<RowData> = Vec::with_capacity(height);

    for row_pixels in &pixels.computed_pixels {
        let mut cells: Vec<CellData> = Vec::with_capacity(width);

        for &(r, g, b) in row_pixels {
            cells.push(CellData {
                user_entered_format: Some(CellFormat {
                    background_color: Some(Color {
                        red: r as f64 / 255.0,
                        green: g as f64 / 255.0,
                        blue: b as f64 / 255.0,
                        alpha: 1.0,
                    }),
                    background_color_style: None,
                    borders: None,
                    horizontal_alignment: None,
                    hyperlink_display_type: None,
                    number_format: None,
                    padding: None,
                    text_direction: None,
                    text_format: None,
                    text_rotation: None,
                    vertical_alignment: None,
                    wrap_strategy: None,
                }),
                data_source_formula: None,
                data_source_table: None,
                data_validation: None,
                effective_format: None,
                effective_value: None,
                formatted_value: String::new(),
                hyperlink: String::new(),
                note: String::new(),
                pivot_table: None,
                text_format_runs: vec![],
                user_entered_value: None,
            });
        }

        rows.push(RowData { values: cells });
    }

    let update_cells = Request {
        add_banding: None,
        add_chart: None,
        add_conditional_format_rule: None,
        add_data_source: None,
        add_dimension_group: None,
        add_filter_view: None,
        add_named_range: None,
        add_protected_range: None,
        add_sheet: None,
        add_slicer: None,
        append_cells: None,
        append_dimension: None,
        auto_fill: None,
        auto_resize_dimensions: None,
        clear_basic_filter: None,
        copy_paste: None,
        create_developer_metadata: None,
        cut_paste: None,
        delete_banding: None,
        delete_conditional_format_rule: None,
        delete_data_source: None,
        delete_developer_metadata: None,
        delete_dimension: None,
        delete_dimension_group: None,
        delete_duplicates: None,
        delete_embedded_object: None,
        delete_filter_view: None,
        delete_named_range: None,
        delete_protected_range: None,
        delete_range: None,
        delete_sheet: None,
        duplicate_filter_view: None,
        duplicate_sheet: None,
        find_replace: None,
        insert_dimension: None,
        insert_range: None,
        merge_cells: None,
        move_dimension: None,
        paste_data: None,
        randomize_range: None,
        refresh_data_source: None,
        repeat_cell: None,
        set_basic_filter: None,
        set_data_validation: None,
        sort_range: None,
        text_to_columns: None,
        trim_whitespace: None,
        unmerge_cells: None,
        update_banding: None,
        update_borders: None,
        update_cells: Some(UpdateCellsRequest {
            fields: "userEnteredFormat.backgroundColor".to_string(),
            range: Some(GridRange {
                sheet_id: 0,
                start_row_index: 0,
                end_row_index: height as i64,
                start_column_index: 0,
                end_column_index: width as i64,
            }),
            rows: rows,
            start: None,
        }),
        update_chart_spec: None,
        update_conditional_format_rule: None,
        update_data_source: None,
        update_developer_metadata: None,
        update_dimension_group: None,
        update_dimension_properties: None,
        update_embedded_object_border: None,
        update_embedded_object_position: None,
        update_filter_view: None,
        update_named_range: None,
        update_protected_range: None,
        update_sheet_properties: None,
        update_slicer_spec: None,
        update_spreadsheet_properties: None,
    };

    let set_col_width = Request {
        add_banding: None,
        add_chart: None,
        add_conditional_format_rule: None,
        add_data_source: None,
        add_dimension_group: None,
        add_filter_view: None,
        add_named_range: None,
        add_protected_range: None,
        add_sheet: None,
        add_slicer: None,
        append_cells: None,
        append_dimension: None,
        auto_fill: None,
        auto_resize_dimensions: None,
        clear_basic_filter: None,
        copy_paste: None,
        create_developer_metadata: None,
        cut_paste: None,
        delete_banding: None,
        delete_conditional_format_rule: None,
        delete_data_source: None,
        delete_developer_metadata: None,
        delete_dimension: None,
        delete_dimension_group: None,
        delete_duplicates: None,
        delete_embedded_object: None,
        delete_filter_view: None,
        delete_named_range: None,
        delete_protected_range: None,
        delete_range: None,
        delete_sheet: None,
        duplicate_filter_view: None,
        duplicate_sheet: None,
        find_replace: None,
        insert_dimension: None,
        insert_range: None,
        merge_cells: None,
        move_dimension: None,
        paste_data: None,
        randomize_range: None,
        refresh_data_source: None,
        repeat_cell: None,
        set_basic_filter: None,
        set_data_validation: None,
        sort_range: None,
        text_to_columns: None,
        trim_whitespace: None,
        unmerge_cells: None,
        update_banding: None,
        update_borders: None,
        update_cells: None,
        update_chart_spec: None,
        update_conditional_format_rule: None,
        update_data_source: None,
        update_developer_metadata: None,
        update_dimension_group: None,
        update_dimension_properties: Some(UpdateDimensionPropertiesRequest {
            data_source_sheet_range: None,
            fields: "pixelSize".to_string(),
            properties: Some(DimensionProperties {
                data_source_column_reference: None,
                developer_metadata: vec![],
                hidden_by_filter: false,
                hidden_by_user: false,
                pixel_size: 5, // 👈 small square pixels
            }),
            range: Some(DimensionRange {
                dimension: Some(Dimension::Columns),
                end_index: width as i64,
                sheet_id: 0,
                start_index: 0,
            }),
        }),
        update_embedded_object_border: None,
        update_embedded_object_position: None,
        update_filter_view: None,
        update_named_range: None,
        update_protected_range: None,
        update_sheet_properties: None,
        update_slicer_spec: None,
        update_spreadsheet_properties: None,
    };

    let set_row_height = Request {
        add_banding: None,
        add_chart: None,
        add_conditional_format_rule: None,
        add_data_source: None,
        add_dimension_group: None,
        add_filter_view: None,
        add_named_range: None,
        add_protected_range: None,
        add_sheet: None,
        add_slicer: None,
        append_cells: None,
        append_dimension: None,
        auto_fill: None,
        auto_resize_dimensions: None,
        clear_basic_filter: None,
        copy_paste: None,
        create_developer_metadata: None,
        cut_paste: None,
        delete_banding: None,
        delete_conditional_format_rule: None,
        delete_data_source: None,
        delete_developer_metadata: None,
        delete_dimension: None,
        delete_dimension_group: None,
        delete_duplicates: None,
        delete_embedded_object: None,
        delete_filter_view: None,
        delete_named_range: None,
        delete_protected_range: None,
        delete_range: None,
        delete_sheet: None,
        duplicate_filter_view: None,
        duplicate_sheet: None,
        find_replace: None,
        insert_dimension: None,
        insert_range: None,
        merge_cells: None,
        move_dimension: None,
        paste_data: None,
        randomize_range: None,
        refresh_data_source: None,
        repeat_cell: None,
        set_basic_filter: None,
        set_data_validation: None,
        sort_range: None,
        text_to_columns: None,
        trim_whitespace: None,
        unmerge_cells: None,
        update_banding: None,
        update_borders: None,
        update_cells: None,
        update_chart_spec: None,
        update_conditional_format_rule: None,
        update_data_source: None,
        update_developer_metadata: None,
        update_dimension_group: None,
        update_dimension_properties: Some(UpdateDimensionPropertiesRequest {
            data_source_sheet_range: None,
            fields: "pixelSize".to_string(),
            properties: Some(DimensionProperties {
                data_source_column_reference: None,
                developer_metadata: vec![],
                hidden_by_filter: false,
                hidden_by_user: false,
                pixel_size: 5,
            }),
            range: Some(DimensionRange {
                dimension: Some(Dimension::Rows),
                end_index: height as i64,
                sheet_id: 0,
                start_index: 0,
            }),
        }),
        update_embedded_object_border: None,
        update_embedded_object_position: None,
        update_filter_view: None,
        update_named_range: None,
        update_protected_range: None,
        update_sheet_properties: None,
        update_slicer_spec: None,
        update_spreadsheet_properties: None,
    };

    // Ensure the sheet has enough columns and rows
    let append_columns = Request {
        add_banding: None,
        add_chart: None,
        add_conditional_format_rule: None,
        add_data_source: None,
        add_dimension_group: None,
        add_filter_view: None,
        add_named_range: None,
        add_protected_range: None,
        add_sheet: None,
        add_slicer: None,
        append_cells: None,
        append_dimension: Some(AppendDimensionRequest {
            dimension: Some(Dimension::Columns),
            length: width as i64,
            sheet_id: 0,
        }),
        auto_fill: None,
        auto_resize_dimensions: None,
        clear_basic_filter: None,
        copy_paste: None,
        create_developer_metadata: None,
        cut_paste: None,
        delete_banding: None,
        delete_conditional_format_rule: None,
        delete_data_source: None,
        delete_developer_metadata: None,
        delete_dimension: None,
        delete_dimension_group: None,
        delete_duplicates: None,
        delete_embedded_object: None,
        delete_filter_view: None,
        delete_named_range: None,
        delete_protected_range: None,
        delete_range: None,
        delete_sheet: None,
        duplicate_filter_view: None,
        duplicate_sheet: None,
        find_replace: None,
        insert_dimension: None,
        insert_range: None,
        merge_cells: None,
        move_dimension: None,
        paste_data: None,
        randomize_range: None,
        refresh_data_source: None,
        repeat_cell: None,
        set_basic_filter: None,
        set_data_validation: None,
        sort_range: None,
        text_to_columns: None,
        trim_whitespace: None,
        unmerge_cells: None,
        update_banding: None,
        update_borders: None,
        update_cells: None,
        update_chart_spec: None,
        update_conditional_format_rule: None,
        update_data_source: None,
        update_developer_metadata: None,
        update_dimension_group: None,
        update_dimension_properties: None,
        update_embedded_object_border: None,
        update_embedded_object_position: None,
        update_filter_view: None,
        update_named_range: None,
        update_protected_range: None,
        update_sheet_properties: None,
        update_slicer_spec: None,
        update_spreadsheet_properties: None,
    };

    let append_rows = Request {
        add_banding: None,
        add_chart: None,
        add_conditional_format_rule: None,
        add_data_source: None,
        add_dimension_group: None,
        add_filter_view: None,
        add_named_range: None,
        add_protected_range: None,
        add_sheet: None,
        add_slicer: None,
        append_cells: None,
        append_dimension: Some(AppendDimensionRequest {
            dimension: Some(Dimension::Rows),
            length: height as i64,
            sheet_id: 0,
        }),
        auto_fill: None,
        auto_resize_dimensions: None,
        clear_basic_filter: None,
        copy_paste: None,
        create_developer_metadata: None,
        cut_paste: None,
        delete_banding: None,
        delete_conditional_format_rule: None,
        delete_data_source: None,
        delete_developer_metadata: None,
        delete_dimension: None,
        delete_dimension_group: None,
        delete_duplicates: None,
        delete_embedded_object: None,
        delete_filter_view: None,
        delete_named_range: None,
        delete_protected_range: None,
        delete_range: None,
        delete_sheet: None,
        duplicate_filter_view: None,
        duplicate_sheet: None,
        find_replace: None,
        insert_dimension: None,
        insert_range: None,
        merge_cells: None,
        move_dimension: None,
        paste_data: None,
        randomize_range: None,
        refresh_data_source: None,
        repeat_cell: None,
        set_basic_filter: None,
        set_data_validation: None,
        sort_range: None,
        text_to_columns: None,
        trim_whitespace: None,
        unmerge_cells: None,
        update_banding: None,
        update_borders: None,
        update_cells: None,
        update_chart_spec: None,
        update_conditional_format_rule: None,
        update_data_source: None,
        update_developer_metadata: None,
        update_dimension_group: None,
        update_dimension_properties: None,
        update_embedded_object_border: None,
        update_embedded_object_position: None,
        update_filter_view: None,
        update_named_range: None,
        update_protected_range: None,
        update_sheet_properties: None,
        update_slicer_spec: None,
        update_spreadsheet_properties: None,
    };

    let body = BatchUpdateSpreadsheetRequest {
        include_spreadsheet_in_response: None,
        requests: vec![append_columns, append_rows, update_cells, set_col_width, set_row_height],
        response_include_grid_data: None,
        response_ranges: vec![],
    };

    let response = spreadsheet.batch_update(spreadsheet_id, &body).await?;

    Ok(response)
}
